- client/src/components/Tamagotchi/index.tsx
- client/src/components/Tamagotchi/main.css
> Implement a loading when a transaction is executing(Play, Sleep, Revive, etc)

- client/package.json
- client/src/components/Header/index.tsx
- client/src/components/Header/main.css
This pull request introduces a new feature to the `Header` component that adds background music with mute/unmute functionality. Additionally, it includes some minor style updates and dependency additions.
* [`client/src/components/Header/index.tsx`](diffhunk://#diff-ab22df0744d85966eeb1aeadc8391b89d5d0a99b9c8451457d97bc9059ef3355L1-R43): Added background music functionality using the `use-sound` hook, including state management for mute/unmute and volume control.
* [`client/src/components/Header/main.css`](diffhunk://#diff-b25a9cde89f8dad594b9aa8e1b902f811c92796130b77b32ba7c428d5bb718a6R69-R97): Added styles for the new sound control button, including hover effects and alignment.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L10-R16): …
> implement music

- Readme.md
- client/src/components/Tamagotchi/index.tsx
- client/src/components/Tamagotchi/main.css
* Empty change for setting branch dev
* fix: triggerGlow
* fix: triggerGlow
> Make sure triggerGlow() is working correctly (#37)

- client/.env.example
- client/.gitignore
- client/src/components/Chat/index.tsx
- client/src/components/Chat/main.css
- client/src/components/ui/message.tsx
- client/src/components/ui/thinking-dots/index.tsx
- client/src/components/ui/thinking-dots/main.css
- client/src/main.tsx
This PR implements a real-time chat interface integrated with ELIZA agent, featuring modern UI/UX elements and smooth interactions.
- Connected chat interface to ELIZA endpoint via Axios
- Implemented message handling with proper error states
- Added environment variable support for ELIZA URL configuration
- Added loading indicators with animated thinking dots
- Implemented auto-scroll to latest messages
- Added input focus management for better UX
- Styled chat container with blur effects and smooth transitions
- Error handling with user-friendly messages
- Message length validation (500 char limit)
- Smooth scrolling behavior
https://www.loom.com/share/9ee7149b1e6141898f1ed67e72725806
Please let me know if you have any questions or feedback.
> feat: integrate eliza agent with the game chat

- Egg_asset_and_animation.md
https://github.com/ByteBuildersLabs/BabyBeastsv2/issues/25
> Create Egg asset and animation

- dojo/src/lib.cairo
- dojo/src/models/beast.cairo
- dojo/src/models/beast_id.cairo
- dojo/src/systems/actions.cairo
- This PR improves the models organization.
> feat: refactor models organization

- dojo/src/constants.cairo
- dojo/src/lib.cairo
- dojo/src/models/beast.cairo
- dojo/src/models/beast_stats.cairo
- dojo/src/models/beast_status.cairo
- dojo/src/systems/actions.cairo
- This PR introduces constants and refactors the Beast model to improve maintainability.  
- The refactor enhances code organization by separating responsibilities and contexts, making the model more modular and easier to extend.
> [FEAT]: Refactor beast models and add constants

- dojo/src/constants.cairo
- dojo/src/systems/actions.cairo
- Closes #52 
- This PR adds a tapping method, once the tap counter reaches the expected value it spawns the beast.
> [FEAT]: Add tap method

- client/dev-dist/sw.js
- client/src/components/Chat/main.css
This PR addresses issue #63  by making the chat page fully responsive across different screen sizes. The chat interface has been adjusted to ensure a smooth and user-friendly experience on mobile, tablet, and desktop views.
- Improved UI scaling for various screen resolutions.
- Fixed layout issues on smaller screens.
1. Run the game and navigate to the chat page.
2. Resize the window or test on different devices.
3. Verify that messages, input fields, and buttons adapt correctly.
- Closes #63
> feat: add responsive to chat page

- dojo/src/constants.cairo
- dojo/src/lib.cairo
- dojo/src/models/food.cairo
- dojo/src/models/player.cairo
- dojo/src/systems/actions.cairo
- dojo/src/types/food.cairo
- Closes #94
- This PR includes the necessary models, types, and methods to enable food usage in the `feed` method.
> [FEAT]: Add food logic

- client/dev-dist/sw.js
- client/src/components/Bag/index.tsx
- client/vite.config.ts
> Migrate Beast Carrusel to "slick-carousel": "^1.8.1"

- client/src/data/characters/bird.character.json
- client/src/data/characters/fox.character.json
- client/src/data/characters/wolf.character.json
-  Closes #97 
Added JSON characters for babybeasts
- Added specific behavior, knowledge and personality for BabyWolf
- Added specific behavior, knowledge and personality for BabyBird
- Added specific behavior, knowledge and personality for BabyFox.
> [FEAT]: Add json characters

- dojo/src/constants.cairo
- dojo/src/systems/actions.cairo
> Move burned values to constants

- dojo/src/systems/actions.cairo
- dojo/src/tests/test_beast.cairo
Closes #84 
Fixed U32 subtraction overflow issues in various game mechanics, primarily in status decrease operations and other stat modifications.
- decrease_status: Added safe subtraction checks for energy, hunger, happiness, and hygiene
- play: Implemented overflow protection for energy and hunger reduction
- revive: Added safe subtraction for attack, defense, and speed stats
- feed: Improved food amount reduction check for consistency
> [FIX]: Fix overflow values

- dojo/src/systems/actions.cairo
- dojo/src/tests/test_status.cairo
- Closes #142 
- Add pet method
- Increases by 5 points the happiness and energy
> [FEAT]: Add pet and tests

- client/dev-dist/sw.js
- client/src/components/Tamagotchi/Actions/index.tsx
- client/src/components/Tamagotchi/Food/index.tsx
- client/vite.config.ts
> Add toast notifications where needed

- client/dev-dist/sw.js
- client/src/components/Tamagotchi/Actions/index.tsx
- client/src/components/Tamagotchi/index.tsx
- client/src/data/initials.tsx
> Add action fot Cuddle tamagotchi

- dojo/src/constants.cairo
- dojo/src/models/beast.cairo
- dojo/src/models/beast_stats.cairo
- dojo/src/models/beast_status.cairo
- dojo/src/models/food.cairo
- dojo/src/models/player.cairo
- dojo/src/store.cairo
- dojo/src/systems/actions.cairo
- dojo/src/tests/test_beast.cairo
- dojo/src/tests/test_food.cairo
- dojo/src/tests/test_player.cairo
- dojo/src/tests/test_stats.cairo
- dojo/src/tests/test_status.cairo
- dojo/src/types/beast.cairo
Closes #185 
This PR optimizes gas consumption by implementing the following improvements:  
- **Added `IntrospectPacked` trait** to enhance model efficiency.  
- **Optimized integer usage** to reduce gas costs.  
- **Modified store food methods** to receive the caller as a parameter.  
- **Removed `#[inline(always)]`** from store functions to improve efficiency.  
- **Deleted the `name` attribute** from the food type to streamline data storage.
> [FEAT]: Optimize gas consuptiom

- dojo/Scarb.lock
- dojo/Scarb.toml
- dojo/src/constants.cairo
- dojo/src/lib.cairo
- dojo/src/models/beast.cairo
- dojo/src/models/beast_stats.cairo
- dojo/src/models/beast_status.cairo
- dojo/src/models/player.cairo
- dojo/src/store.cairo
- dojo/src/systems/actions.cairo
- dojo/src/tests/test_actions.cairo
- dojo/src/tests/test_beast.cairo
- dojo/src/tests/test_food.cairo
- dojo/src/tests/test_player.cairo
- dojo/src/tests/test_stats.cairo
- dojo/src/tests/test_status.cairo
- dojo/src/tests/utils.cairo
- dojo/src/types/beast.cairo
- dojo/src/types/clean_status.cairo
- dojo/src/types/food.cairo
This PR upgrades the Dojo contracts to **version 1.2.1** and **Cairo 2.9.2**, incorporating the following updates:  
- **Updated imports** to align with the latest version.  
- **Refactored unit tests** for compatibility and improved reliability.  
- **Enhanced visibility** of entities and methods for better accessibility and maintainability.  
- sozo build ✅ 
- sozo test ✅
> [FEAT]: Upgrade all game to latest Dojo version

- client/dev-dist/sw.js
- client/src/components/SpawnBeast/index.tsx
- client/src/components/Tamagotchi/index.tsx
- client/src/components/Tamagotchi/main.css
- client/vite.config.ts
- The button takes you to the spawn screen
- Remove all the previous status
- This one closes https://github.com/ByteBuildersLabs/Tamagotchi/issues/222
> Add a new egg button

- client/src/components/Leadeboard/index.tsx
- client/src/hooks/useBeasts.tsx
- Collect unique player addresses from tamagotchiBeastModels.
- Fetch usernames for all addresses using lookupAddresses.
- Add userName property to each beast object in playerData.
> Added userName to playerData by mapping player addresses.

- client/dev-dist/sw.js
- client/src/components/Leadeboard/index.tsx
- client/src/components/SpawnBeast/index.tsx
- client/src/components/Tamagotchi/index.tsx
- client/vite.config.ts
- Now If the beast is death, It gonna show the graveyard, letting the person know the beast is death (before It was jumping to the spawn page)
- Added a reborn key to LS to know If the person is spawning a new beast
- Removed the message and left only the button
> Fix death state for tamagotchi and add reborn state

- client/src/config/cartridgeConnector.tsx
> Add ByteBeasts-Tamagotchi theme

- dojo/src/models/beast_status.cairo
> Decrease stats more accurate

- dojo/src/models/food.cairo
- dojo/src/models/player.cairo
- dojo/src/store.cairo
- dojo/src/systems/game.cairo
- dojo/src/systems/player.cairo
- dojo/src/tests/test_food.cairo
- dojo/src/tests/test_player.cairo
Closes #257 
Status: Done - Player Ready / Food Ready
> [FEAT]: add total points for players and update food

- dojo/src/constants.cairo
- dojo/src/lib.cairo
- dojo/src/models/beast_status.cairo
- dojo/src/store.cairo
- dojo/src/systems/game.cairo
- dojo/src/tests/test_status.cairo
- dojo/src/types/beast_status_custom.cairo
- Ticket: [BB-9](https://bytebeasts.atlassian.net/browse/BB-11)
> BB-9: Fix decrease status mechanics and add tests

- dojo/src/models/beast_status.cairo
- dojo/src/store.cairo
- dojo/src/systems/game.cairo
- dojo/src/tests/test_beast.cairo
> Fix status not decreasing

- client/src/components/Leadeboard/index.tsx
Modified the sorting logic to order birth_date in ascending order (from oldest to youngest) when ages are equal.
Ticket BB-32: https://bytebeasts.atlassian.net/jira/software/projects/BB/boards/1?selectedIssue=BB-32
> Modified the sorting logic to order birth_date in ascending order.

- client/dev-dist/sw.js
- client/src/components/Tamagotchi/Chat/index.tsx
- client/src/components/Tamagotchi/Whispers/index.tsx
📝 Change Description
Simplified message generation by removing generateLore, generateAdvise, and generateStatus.
createWhisper now displays random predefined messages instead of sending prompts.
Cleaned up duplicate code and unused references.
Kept the 3-minute interval to show quick, simple messages.
> Fix AI Agent whisper

- dojo/src/store.cairo
- dojo/src/systems/game.cairo
- Update the read method to calculate age of the beast
> Update read method

- client/dev-dist/sw.js
- client/src/components/SkyJumpMiniGame/index.tsx
- client/src/components/SkyJumpMiniGame/main.css
- client/vite.config.ts
Closes BB-69
Changes:
- Enhanced food img render by preloading the images into and array before to start the minigame
- Enhanced radomness to choose the food, now it feels more natural
- Fixed fetchStatus method to get the beast's energy before to play again
> [FEAT] Minor fixes to minigame

- client/dev-dist/sw.js
- client/src/components/Leadeboard/index.tsx
- client/src/components/SkyJumpMiniGame/index.tsx
- client/src/config/cartridgeConnector.tsx
- client/src/dojo/bindings.ts
- client/src/dojo/contracts.gen.ts
- client/src/dojo/dojoConfig.ts
- client/src/dojo/manifest_dev.json
- client/src/hooks/useFood.tsx
- client/src/hooks/useHighScore.tsx
- client/src/utils/tamagotchi.tsx
- client/vite.config.ts
- dojo/bindings/typescript/contracts.gen.ts
- dojo/bindings/typescript/models.gen.ts
- dojo/dojo_dev.toml
- dojo/dojo_slot.toml
- dojo/manifest_dev.json
- dojo/torii-config.toml
- This one closes this https://bytebeasts.atlassian.net/browse/BB-67
- And prepare the implementation for high score
> Set high score integration and new torii config

- client/dev-dist/sw.js
- client/src/config/cartridgeConnector.tsx
- client/src/dojo/dojoConfig.ts
- client/src/dojo/manifest_dev.json
- dojo/dojo_dev.toml
- dojo/dojo_slot.toml
- dojo/manifest_dev.json
- dojo/torii-config.toml
This one closes this one
- https://bytebeasts.atlassian.net/browse/BB-83
> new deploy to fix torii and set official katana and torii

- client/env.d.ts
- client/src/config/cartridgeConnector.tsx
- client/src/config/manifest.ts
> [REFACTOR]: remove slot support and update deployment logic

- client/src/utils/events.ts
This PR introduces a centralized and type-safe structure for PostHog event tracking, laying the foundation for analytics integration in the project.
- Created `utils/events.ts` to define all analytics event constants
- Grouped events by category: Session, Core Interactions, Mini Games, Social.
- Exported `EventGroup`, `EVENTS`, and `EventName` types for reuse and type safety
This structure ensures consistency across the codebase and makes future expansion easy and maintainable.
> [FEAT]: Add event tracking enums and constants.

- client/dev-dist/sw.js
- client/src/components/SpawnBeast/index.tsx
- client/src/components/Tamagotchi/components/BeastDisplay.tsx
- client/src/components/Tamagotchi/index.tsx
- client/src/dojo/useSystemCalls.ts
- client/src/hooks/useBeasts.tsx
- client/src/hooks/usePlayers.tsx
- client/src/hooks/useTamagotchi.ts
- client/src/index.css
- client/vite.config.ts
Ticket: https://bytebeasts.atlassian.net/browse/BB-114
> Make sure the first hatch fetch the status properly

- client/.env
- client/dev-dist/sw.js
- client/src/components/Tamagotchi/Actions/index.tsx
- client/src/components/Tamagotchi/utils/fetchAge.ts
- client/src/components/Tamagotchi/utils/fetchStatus.ts
- client/src/config/cartridgeConnector.tsx
- client/src/dojo/dojoConfig.ts
- client/src/dojo/manifest_dev.json
- client/src/hooks/useTamagotchi.ts
- client/vite.config.ts
This one closes this
https://bytebeasts.atlassian.net/browse/BB-112
> Integreate BeastCare achievements

- client/dev-dist/sw.js
- client/src/components/SpawnBeast/components/SpawnButton.tsx
This one closes this
https://bytebeasts.atlassian.net/browse/BB-129
> Delete spinner in hatch egg

- client/dev-dist/sw.js
- client/src/components/FlappyBeasts/flappyBeasts.tsx
- client/src/components/Header/index.tsx
- client/src/components/SkyJumpMiniGame/index.tsx
- client/src/components/SpawnBeast/index.tsx
- client/src/components/Tamagotchi/Actions/index.tsx
- client/src/components/Tamagotchi/Chat/index.tsx
- client/src/components/Tamagotchi/Play/index.tsx
- client/src/components/Tamagotchi/index.tsx
- client/src/components/Twitter/ShareProgress.tsx
- client/src/config/cartridgeConnector.tsx
- client/src/dojo/contracts.gen.ts
- client/src/dojo/manifest_dev.json
- client/src/hooks/useTamagotchi.ts
- client/vite.config.ts
> Integrete Minigames achievements and Social achievements

- client/src/components/FlappyBeasts/flappyBeasts.tsx
- client/src/components/FlappyBeasts/main.css
- client/src/components/Header/index.tsx
- client/src/components/Tamagotchi/Actions/index.tsx
- client/src/components/ui/ModalGameOver/ModalGameOver.tsx
- client/vite.config.ts
Ticket https://bytebeasts.atlassian.net/browse/BB-130
- Fix close button for flappy game
- Set back the aura for actions box when loading
- Remove banner for tournament
- Fix hatch error
> UI fixes + fix hatch error
